spring.application.name=train-reservation-system

spring.datasource.url=jdbc:h2:file:./traindb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
spring.mustache.charset=UTF-8
spring.mustache.check-template-location=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:db/data/data.sql